apiVersion: v1
kind: Service
metadata:
   name: {{ .Values.nginx.service.name }}
   namespace: {{ .Values.namespace }}
spec:
   selector:
      app: {{ .Values.nginx.service.app }}
   ports:
      - port: {{ .Values.nginx.service.port }}
        targetPort: {{ .Values.nginx.service.targetPort }}