apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ .Values.cast.hpa.name }}
 namespace: {{ .Values.namespace }}
spec:
 scaleTargetRef:
   apiVersion: {{ .Values.cast.hpa.scaleTargetRef.apiVersion }}
   kind: {{ .Values.cast.hpa.scaleTargetRef.kind }}
   name: {{ .Values.cast.hpa.scaleTargetRef.name }}
 minReplicas: {{ .Values.cast.hpa.minReplicas }}
 maxReplicas: {{ .Values.cast.hpa.maxReplicas }}
 targetCPUUtilizationPercentage: {{ .Values.cast.hpa.targetCPU }}