apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.moviePostgres.secret.name }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.moviePostgres.secret.type }}
data:
  POSTGRES_USER: {{ .Values.moviePostgres.secret.user }}
  POSTGRES_PASSWORD: {{ .Values.moviePostgres.secret.password }}
  POSTGRES_DB: {{ .Values.moviePostgres.secret.db }}