apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.moviePostgres.service.nameApp }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.moviePostgres.service.nameApp }}
spec:
  selector:
    app: {{ .Values.moviePostgres.service.nameApp }}
  ports:
  - name: {{ .Values.moviePostgres.service.nameApp }}
    port: {{ .Values.moviePostgres.service.port }}
    targetPort: {{ .Values.moviePostgres.service.targetPort }}
  clusterIP: {{ .Values.moviePostgres.service.clusterIP }}